# Generated by Django 5.2.16 on 2026-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_historicalcashvoucher_historicalinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
