# Generated by Django 5.2.16 on 2026-07-30 14:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_historicalinvoice_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalloan',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Originating bank account number', max_length=50),
        ),
        migrations.AddField(
            model_name='capitalloan',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Issue date of physical cheque', null=True),
        ),
        migrations.AddField(
            model_name='capitalloan',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Physical paper cheque reference number', max_length=50),
        ),
        migrations.AddField(
            model_name='capitalloan',
            name='logistics_deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Percentage of upfront logistics deposit funded (Default 50%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='cashvoucher',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Issue date of physical cheque', null=True),
        ),
        migrations.AddField(
            model_name='cashvoucher',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Physical paper cheque reference number', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcashvoucher',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Issue date of physical cheque', null=True),
        ),
        migrations.AddField(
            model_name='historicalcashvoucher',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Physical paper cheque reference number', max_length=50),
        ),
    ]
