# Generated by Django 5.2.16 on 2026-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_capitalloan_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalloan',
            name='settlement_date',
            field=models.DateField(blank=True, help_text='Date facility was officially settled', null=True),
        ),
        migrations.AddField(
            model_name='capitalloan',
            name='settlement_document',
            field=models.FileField(blank=True, help_text='Scanned soft copy of Bank Release Clearance Advice / Receipt', null=True, upload_to='loan_settlements/'),
        ),
        migrations.AddField(
            model_name='capitalloan',
            name='settlement_notes',
            field=models.TextField(blank=True, help_text='Notes on final loan settlement'),
        ),
        migrations.AddField(
            model_name='capitalloan',
            name='settlement_receipt_number',
            field=models.CharField(blank=True, help_text='Bank Release Advice / Official Receipt Number', max_length=100),
        ),
    ]
