# Generated by Django 5.2.16 on 2026-08-21 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_capitalloan_settlement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalloan',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Audit notes on loan creation or settlement verification'),
        ),
        migrations.AddField(
            model_name='capitalloan',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitalloan',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Operations Manager or Administrator who verified this loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capitalloan',
            name='status',
            field=models.CharField(choices=[('pending_creation', 'Pending Creation Approval'), ('active', 'Active Facility'), ('pending_settlement', 'Pending Settlement Approval'), ('closed', 'Settled & Closed'), ('overdue', 'Overdue'), ('rejected', 'Verification Rejected')], default='pending_creation', max_length=30),
        ),
    ]
