# Generated by Django 5.2.16 on 2026-08-28 09:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_capitalloan_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='tax_rate_ewt',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='EWT Rate (%)'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='tax_rate_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='VAT Rate (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate_ewt',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='EWT Rate (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='VAT Rate (%)'),
        ),
    ]
