# Generated by Django 5.2.16 on 2026-08-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_historicalinvoice_tax_rate_ewt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashvoucher',
            name='loan',
            field=models.ForeignKey(blank=True, help_text='Capital Loan Facility backing this outlay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_vouchers', to='finance.capitalloan'),
        ),
        migrations.AddField(
            model_name='historicalcashvoucher',
            name='loan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Capital Loan Facility backing this outlay', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.capitalloan'),
        ),
    ]
