# Generated by Django 5.2.16 on 2026-10-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_historicalinvoice_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='incremental_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Specified incremental billing percentage (e.g., 50.00, 25.00)', max_digits=5, null=True, verbose_name='Incremental Portion (%)'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='is_incremental',
            field=models.BooleanField(default=False, help_text='Designates this invoice as an incremental progress billing (e.g. 50%, 25% partial invoice)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='incremental_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Specified incremental billing percentage (e.g., 50.00, 25.00)', max_digits=5, null=True, verbose_name='Incremental Portion (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_incremental',
            field=models.BooleanField(default=False, help_text='Designates this invoice as an incremental progress billing (e.g. 50%, 25% partial invoice)'),
        ),
    ]
