# Generated by Django 5.2.16 on 2026-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_incremental_invoice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentexpensematch',
            name='expense_type',
            field=models.CharField(choices=[('sourcing', 'Sourcing'), ('trucking', 'Trucking Fees'), ('tracking', 'Trucking Fees'), ('barge', 'Barge Fees'), ('logistics_deposit', '50% Logistics Deposit'), ('other', 'Other')], max_length=30),
        ),
    ]
