# Generated by Django 5.2.16 on 2026-07-30 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/clients/'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Relationship & operational overview notes'),
        ),
        migrations.AddField(
            model_name='sugarmill',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/mills/'),
        ),
        migrations.AddField(
            model_name='sugarmill',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sugarmill',
            name='notes',
            field=models.TextField(blank=True, help_text='Capability & supply relationship notes'),
        ),
        migrations.CreateModel(
            name='PartnerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='masters.client')),
                ('sugar_mill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='masters.sugarmill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
