from django.urls import path

from . import views

app_name = "operations"

urlpatterns = [
    path("", views.cluster_list, name="cluster_list"),
    path("logistics/", views.logistics_list, name="logistics_list"),
    path("logistics/export/", views.export_logistics_csv, name="export_logistics_csv"),
    path("import/", views.import_excel, name="import_excel"),
    path("clear-database/", views.clear_database_view, name="clear_database"),
    path("new/", views.cluster_create, name="cluster_create"),
    path("<uuid:pk>/", views.cluster_detail, name="cluster_detail"),
    path("<uuid:pk>/edit/", views.cluster_edit, name="cluster_edit"),
    path("<uuid:pk>/logistics/", views.update_logistics, name="update_logistics"),
    path("<uuid:pk>/invoice/", views.add_invoice, name="add_invoice"),
    path("<uuid:pk>/voucher/", views.add_voucher, name="add_voucher"),
    path("<uuid:pk>/loan/", views.add_loan, name="add_loan"),
    path("invoice/<int:invoice_pk>/status/", views.update_invoice_status, name="update_invoice_status"),
    path("<uuid:pk>/resolve-dispute/", views.resolve_dispute, name="resolve_dispute"),
    path("archive/", views.archive_list, name="archive_list"),
    path("bulk-archive/", views.bulk_archive_completed, name="bulk_archive_completed"),
    path("<uuid:pk>/archive/", views.archive_cluster, name="archive_cluster"),
    path("<uuid:pk>/unarchive/", views.unarchive_cluster, name="unarchive_cluster"),
    path("<uuid:pk>/delete/", views.delete_cluster, name="delete_cluster"),
    path("<uuid:pk>/upload-mro/", views.upload_mro, name="upload_mro"),
    path("mro-summary/", views.mro_summary_view, name="mro_summary"),
    path("mro-summary/create/", views.mro_create_view, name="mro_create"),
    path("mro-summary/<int:pk>/edit/", views.mro_edit_view, name="mro_edit"),
    path("mro-summary/<int:pk>/delete/", views.mro_delete_view, name="mro_delete"),
    path("mro-summary/import/", views.mro_import_excel_view, name="mro_import_excel"),
    path("mro-summary/export/", views.mro_export_csv_view, name="mro_export_csv"),
    path("<uuid:pk>/link-mro/", views.link_mro_to_cluster, name="link_mro"),
    path("<uuid:pk>/unlink-mro/<int:mro_pk>/", views.unlink_mro_from_cluster, name="unlink_mro"),
    path("<uuid:pk>/contract/pdf/", views.download_contract_pdf, name="download_contract_pdf"),
    path("<uuid:pk>/po/pdf/", views.download_po_pdf, name="download_po_pdf"),
    path("api/copilot/query/", views.copilot_query_api, name="copilot_query_api"),
    path("api/generate-references/", views.generate_reference_api, name="generate_reference_api"),
    path("api/predict-trade-terms/", views.predict_trade_terms_api, name="predict_trade_terms_api"),
    path("chai/", views.chai_list, name="chai_list"),
    path("chai/create/", views.chai_create, name="chai_create"),
    path("chai/<uuid:pk>/", views.chai_detail, name="chai_detail"),
    path("chai/<uuid:pk>/edit/", views.chai_edit, name="chai_edit"),
    path("chai/<uuid:pk>/delete/", views.chai_delete, name="chai_delete"),
    path("chai/export/", views.export_chai_csv, name="export_chai_csv"),
    path("<uuid:pk>/submit/", views.submit_cluster_for_approval, name="submit_cluster"),
    path("<uuid:pk>/approve/", views.approve_cluster, name="approve_cluster"),
    path("<uuid:pk>/reject/", views.reject_cluster, name="reject_cluster"),
    path("chai/<uuid:pk>/approve/", views.approve_chai, name="approve_chai"),
    path("chai/<uuid:pk>/reject/", views.reject_chai, name="reject_chai"),
    path("pending-tasks/", views.pending_tasks_view, name="pending_tasks"),
    path("stats-monitoring/", views.stats_monitoring_view, name="stats_monitoring"),
    path("api/stats-check/", views.stats_check_api, name="stats_check_api"),
]


