# Generated by Django 5.2.16 on 2026-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System-generated operational alert'),
        ),
    ]
