# Generated by Django 5.2.16 on 2026-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('management', 'Management'), ('operations_manager', 'Operations Manager'), ('finance', 'Finance Officer'), ('operations', 'Operations Staff'), ('invoicing', 'Invoicing Staff')], default='operations', max_length=20),
        ),
    ]
