# Generated by Django 5.2.16 on 2026-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('operations_management', 'Operations Management'), ('finance', 'Finance'), ('invoicing', 'Invoicing')], default='operations_management', max_length=30),
        ),
    ]
