# Generated by Django 5.2.16 on 2026-09-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('approval', 'Approval'), ('variance', 'Variance Alert'), ('logistics', 'Logistics'), ('loan', 'Loan Facility'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
