# Generated by Django 5.2.15 on 2026-06-23 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('contract_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='masters.client')),
                ('sugar_mill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='masters.sugarmill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_mt', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terms', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='operations.transactioncluster')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_id', models.CharField(blank=True, max_length=100)),
                ('loaded_volume_mt', models.DecimalField(decimal_places=3, max_digits=14)),
                ('received_volume_mt', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('barge_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('variance_exceeds_tolerance', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.logisticspartner')),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='operations.transactioncluster')),
            ],
        ),
    ]
