# Generated by Django 5.2.16 on 2026-07-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_historicallogisticsledger_historicalpurchaseorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='dispute_status',
            field=models.CharField(choices=[('NONE', 'None'), ('DISPUTED', 'Disputed — Over Tolerance'), ('RESOLVED', 'Resolved')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('CONCEDED', 'Concede & Proceed As-Is'), ('BILLING_ADJUSTED', 'Adjust Billing to Received Volume'), ('BARGE_PENALTY', 'Deduct Shortage Penalty from Logistics'), ('WAIVED', 'Management Waiver (Brix / Evaporation)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='dispute_status',
            field=models.CharField(choices=[('NONE', 'None'), ('DISPUTED', 'Disputed — Over Tolerance'), ('RESOLVED', 'Resolved')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('CONCEDED', 'Concede & Proceed As-Is'), ('BILLING_ADJUSTED', 'Adjust Billing to Received Volume'), ('BARGE_PENALTY', 'Deduct Shortage Penalty from Logistics'), ('WAIVED', 'Management Waiver (Brix / Evaporation)')], max_length=30, null=True),
        ),
    ]
