# Generated by Django 5.2.16 on 2026-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_historicallogisticsledger_dispute_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
