# Generated by Django 5.2.16 on 2026-07-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_historicallogisticsledger_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='mro_file',
            field=models.TextField(blank=True, help_text='Scanned soft copy of Molasses Release Order (PDF/Image)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='mro_file',
            field=models.FileField(blank=True, help_text='Scanned soft copy of Molasses Release Order (PDF/Image)', null=True, upload_to='mro_scans/'),
        ),
    ]
