# Generated by Django 5.2.16 on 2026-08-19 09:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_planter'),
        ('operations', '0005_historicaltransactioncluster_mro_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMolassesReleaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mro_number', models.CharField(db_index=True, max_length=50, verbose_name='MRO #')),
                ('tons', models.DecimalField(decimal_places=5, max_digits=14, verbose_name='Tons (MT)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('trader', models.CharField(default='HEINDRICH', max_length=120, verbose_name='Trader')),
                ('crop_year', models.CharField(db_index=True, max_length=30, verbose_name='Crop Year')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cluster', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional transaction cluster contract linkage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.transactioncluster')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.planter')),
            ],
            options={
                'verbose_name': 'historical Molasses Release Order',
                'verbose_name_plural': 'historical Molasses Release Orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MolassesReleaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mro_number', models.CharField(db_index=True, max_length=50, verbose_name='MRO #')),
                ('tons', models.DecimalField(decimal_places=5, max_digits=14, verbose_name='Tons (MT)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('trader', models.CharField(default='HEINDRICH', max_length=120, verbose_name='Trader')),
                ('crop_year', models.CharField(db_index=True, max_length=30, verbose_name='Crop Year')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, help_text='Optional transaction cluster contract linkage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mro_releases', to='operations.transactioncluster')),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mro_releases', to='masters.planter')),
            ],
            options={
                'verbose_name': 'Molasses Release Order',
                'verbose_name_plural': 'Molasses Release Orders',
                'ordering': ['-crop_year', 'mro_number', 'planter__name', 'id'],
            },
        ),
    ]
