# Generated by Django 5.2.16 on 2026-08-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_planter'),
        ('operations', '0006_historicalmolassesreleaseorder_molassesreleaseorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molassesreleaseorder',
            options={'ordering': ['sugar_mill_name', '-crop_year', 'mro_number', 'planter__name', 'id'], 'verbose_name': 'Molasses Release Order', 'verbose_name_plural': 'Molasses Release Orders'},
        ),
        migrations.AddField(
            model_name='historicalmolassesreleaseorder',
            name='sugar_mill',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Issuing Sugar Mill / Supplier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.sugarmill'),
        ),
        migrations.AddField(
            model_name='historicalmolassesreleaseorder',
            name='sugar_mill_name',
            field=models.CharField(blank=True, help_text='Supplier/Mill name fallback', max_length=120, verbose_name='Supplier / Sugar Mill'),
        ),
        migrations.AddField(
            model_name='molassesreleaseorder',
            name='sugar_mill',
            field=models.ForeignKey(blank=True, help_text='Issuing Sugar Mill / Supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mro_releases', to='masters.sugarmill'),
        ),
        migrations.AddField(
            model_name='molassesreleaseorder',
            name='sugar_mill_name',
            field=models.CharField(blank=True, help_text='Supplier/Mill name fallback', max_length=120, verbose_name='Supplier / Sugar Mill'),
        ),
    ]
