# Generated by Django 5.2.16 on 2026-08-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_molassesreleaseorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='dr_file',
            field=models.TextField(blank=True, help_text='Scanned soft copy of Delivery Receipt (DR)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='waybill_file',
            field=models.TextField(blank=True, help_text='Scanned soft copy of Waybill', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmolassesreleaseorder',
            name='brix_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Brix quality level', max_digits=5, null=True, verbose_name='Brix Level (%)'),
        ),
        migrations.AddField(
            model_name='historicalmolassesreleaseorder',
            name='chai_specs',
            field=models.CharField(blank=True, help_text='Chemical / CHAI quality specs', max_length=120, verbose_name='CHAI Specs'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='brix_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target / Verified Brix % quality level', max_digits=5, null=True, verbose_name='Brix Level (%)'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='chai_specs',
            field=models.CharField(blank=True, help_text='Chemical / CHAI specifications', max_length=120, verbose_name='CHAI Specs'),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='dr_file',
            field=models.FileField(blank=True, help_text='Scanned soft copy of Delivery Receipt (DR)', null=True, upload_to='delivery_receipts/'),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='waybill_file',
            field=models.FileField(blank=True, help_text='Scanned soft copy of Waybill', null=True, upload_to='waybills/'),
        ),
        migrations.AddField(
            model_name='molassesreleaseorder',
            name='brix_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Brix quality level', max_digits=5, null=True, verbose_name='Brix Level (%)'),
        ),
        migrations.AddField(
            model_name='molassesreleaseorder',
            name='chai_specs',
            field=models.CharField(blank=True, help_text='Chemical / CHAI quality specs', max_length=120, verbose_name='CHAI Specs'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='brix_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target / Verified Brix % quality level', max_digits=5, null=True, verbose_name='Brix Level (%)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='chai_specs',
            field=models.CharField(blank=True, help_text='Chemical / CHAI specifications', max_length=120, verbose_name='CHAI Specs'),
        ),
    ]
