# Generated by Django 5.2.16 on 2026-08-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_planter'),
        ('operations', '0008_historicallogisticsledger_dr_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='barge_partner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Marine Transport / Barging Service Provider', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.logisticspartner'),
        ),
        migrations.AddField(
            model_name='historicallogisticsledger',
            name='trucking_partner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Land Transport / Trucking Service Provider', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.logisticspartner'),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='barge_partner',
            field=models.ForeignKey(blank=True, help_text='Marine Transport / Barging Service Provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barge_ledgers', to='masters.logisticspartner'),
        ),
        migrations.AddField(
            model_name='logisticsledger',
            name='trucking_partner',
            field=models.ForeignKey(blank=True, help_text='Land Transport / Trucking Service Provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucking_ledgers', to='masters.logisticspartner'),
        ),
        migrations.AlterField(
            model_name='logisticsledger',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.logisticspartner'),
        ),
    ]
