# Generated by Django 5.2.16 on 2026-08-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_historicallogisticsledger_barge_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price billed to customer', max_digits=12, null=True, verbose_name='Customer Selling Price (₱/MT)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price billed to customer', max_digits=12, null=True, verbose_name='Customer Selling Price (₱/MT)'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Supplier Sourcing Price (₱/MT)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Supplier Sourcing Price (₱/MT)'),
        ),
    ]
