# Generated by Django 5.2.16 on 2026-09-25 02:29

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_planter'),
        ('operations', '0010_historicalpurchaseorder_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CHAIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chai_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='CHAI Record Code')),
                ('chai_value', models.DecimalField(choices=[(Decimal('1.0'), 'CHAI 1.0 — Premium Grade A (Brix 85°+ / High Fermentable Sugar)'), (Decimal('1.5'), 'CHAI 1.5 — Superior Grade A- (Brix 83.0° - 84.9°)'), (Decimal('2.0'), 'CHAI 2.0 — Standard Commercial Grade B (Brix 80.0° - 82.9°)'), (Decimal('2.5'), 'CHAI 2.5 — Medium Commercial Grade B- (Brix 78.0° - 79.9°)'), (Decimal('3.0'), 'CHAI 3.0 — Industrial Distillation Grade C (Brix 75.0° - 77.9°)'), (Decimal('3.5'), 'CHAI 3.5 — Utility Grade C- (Brix 72.0° - 74.9°)'), (Decimal('4.0'), 'CHAI 4.0 — Low Grade D (Brix 70.0° - 71.9°)'), (Decimal('5.0'), 'CHAI 5.0 — Substandard / Off-Spec (< 70.0° Brix)')], decimal_places=1, default=Decimal('1.0'), help_text='Standard numerical quality grade (1.0 to 5.0)', max_digits=4, verbose_name='Numerical CHAI Grade')),
                ('title', models.CharField(help_text='e.g. Verified High Brix Distillation Quality', max_length=200, verbose_name='Quality Title / Summary')),
                ('brix_level', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5, verbose_name='Brix Level (%)')),
                ('purity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Apparent Purity (%)')),
                ('total_sugars_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Sugars (%)')),
                ('tested_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Inspection Date')),
                ('inspector', models.CharField(blank=True, max_length=120, verbose_name='Inspector / Analyst')),
                ('status', models.CharField(choices=[('approved', 'Approved / Verified'), ('pending', 'Pending Verification'), ('rejected', 'Rejected / Off-Spec')], default='approved', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Inspection Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, help_text='Optional linked contract transaction deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chai_records', to='operations.transactioncluster')),
                ('sugar_mill', models.ForeignKey(blank=True, help_text='Tested Sugar Mill / Supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chai_records', to='masters.sugarmill')),
            ],
            options={
                'verbose_name': 'CHAI Record',
                'verbose_name_plural': 'CHAI Records',
                'ordering': ['-tested_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCHAIRecord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('chai_number', models.CharField(db_index=True, max_length=50, verbose_name='CHAI Record Code')),
                ('chai_value', models.DecimalField(choices=[(Decimal('1.0'), 'CHAI 1.0 — Premium Grade A (Brix 85°+ / High Fermentable Sugar)'), (Decimal('1.5'), 'CHAI 1.5 — Superior Grade A- (Brix 83.0° - 84.9°)'), (Decimal('2.0'), 'CHAI 2.0 — Standard Commercial Grade B (Brix 80.0° - 82.9°)'), (Decimal('2.5'), 'CHAI 2.5 — Medium Commercial Grade B- (Brix 78.0° - 79.9°)'), (Decimal('3.0'), 'CHAI 3.0 — Industrial Distillation Grade C (Brix 75.0° - 77.9°)'), (Decimal('3.5'), 'CHAI 3.5 — Utility Grade C- (Brix 72.0° - 74.9°)'), (Decimal('4.0'), 'CHAI 4.0 — Low Grade D (Brix 70.0° - 71.9°)'), (Decimal('5.0'), 'CHAI 5.0 — Substandard / Off-Spec (< 70.0° Brix)')], decimal_places=1, default=Decimal('1.0'), help_text='Standard numerical quality grade (1.0 to 5.0)', max_digits=4, verbose_name='Numerical CHAI Grade')),
                ('title', models.CharField(help_text='e.g. Verified High Brix Distillation Quality', max_length=200, verbose_name='Quality Title / Summary')),
                ('brix_level', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5, verbose_name='Brix Level (%)')),
                ('purity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Apparent Purity (%)')),
                ('total_sugars_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Sugars (%)')),
                ('tested_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Inspection Date')),
                ('inspector', models.CharField(blank=True, max_length=120, verbose_name='Inspector / Analyst')),
                ('status', models.CharField(choices=[('approved', 'Approved / Verified'), ('pending', 'Pending Verification'), ('rejected', 'Rejected / Off-Spec')], default='approved', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Inspection Notes')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cluster', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional linked contract transaction deal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.transactioncluster')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sugar_mill', models.ForeignKey(blank=True, db_constraint=False, help_text='Tested Sugar Mill / Supplier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.sugarmill')),
            ],
            options={
                'verbose_name': 'historical CHAI Record',
                'verbose_name_plural': 'historical CHAI Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
