# Generated by Django 5.2.16 on 2026-09-25 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_chairecord_historicalchairecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chairecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chairecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_chai_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chairecord',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chairecord',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_chai_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chairecord',
            name='rejection_comments',
            field=models.TextField(blank=True, default='', help_text='Mandatory reason for returning / rejecting CHAI certificate', verbose_name='Rejection Comments'),
        ),
        migrations.AddField(
            model_name='historicalchairecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchairecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalchairecord',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchairecord',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalchairecord',
            name='rejection_comments',
            field=models.TextField(blank=True, default='', help_text='Mandatory reason for returning / rejecting CHAI certificate', verbose_name='Rejection Comments'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='rejection_comments',
            field=models.TextField(blank=True, default='', help_text='Mandatory comments detailing rejection/return reason'),
        ),
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='rejection_comments',
            field=models.TextField(blank=True, default='', help_text='Mandatory reason for returning / rejecting the transaction'),
        ),
        migrations.AddField(
            model_name='historicaltransactioncluster',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejection_comments',
            field=models.TextField(blank=True, default='', help_text='Mandatory comments detailing rejection/return reason'),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clusters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_clusters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='rejection_comments',
            field=models.TextField(blank=True, default='', help_text='Mandatory reason for returning / rejecting the transaction'),
        ),
        migrations.AddField(
            model_name='transactioncluster',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncluster',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('returned', 'Returned / Rejected'), ('active', 'Active'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactioncluster',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('returned', 'Returned / Rejected'), ('active', 'Active'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
